### ISSUE TITLE
Request to remove the filter that blocks Railcraft Reborn messages

### ISSUE THREAD

**Issue by Edivad99** [JDKDigital/utilitarian#1]
Good morning,
I'm one of two developers at Railcraft Reborn who writes.
I wanted to invite you to at least remove the config that blocks messages informing the player that a new update is available.
I would like to take this opportunity to inform you that since October we have added a config that allows the player to silence messages relating to the beta version. https://github.com/railcraft-reborn/railcraft/commit/f28d2f7009cb32f628307bbcff50a734bf281401

**Comment by JaisDK** [comment]
ok, if you include your own config then I'll just remove the RC messages from the default config next time I update

**Comment by Edivad99** [comment]
Thanks, this config is already present in
- 1.0.9
- 1.0.10
- 1.1.0

**Comment by JaisDK** [comment]
removed in latest version
