### ISSUE TITLE
Add a config option to blacklist specific items from the Hoe Planting module

### ISSUE THREAD

**Issue by NarrikSynthfox** [JDKDigital/utilitarian#2]
I've encountered some weird behavior with the rice seeds from Sushi Go Crafting, because normally they'd get placed underwater. When they get placed when tilling land, it creates a water block that they are in, and removing the seed results in the water spreading. Even if that's the only one at the moment, it would be good to have a blacklist of seeds that don't get auto-planted for this and the future if any cause issues.

**Comment by JaisDK** [comment]
I added the tag but also added support for water based seeds. Thanks for reporting!
