### ISSUE TITLE
[1.21] Raw_block to block recipes use old tags

### ISSUE THREAD

**Issue by WhitePhant0m** [JDKDigital/utilitarian#4]
Gold, Iron, and Copper raw block to block smelting/blasting recipes use `forge:storage_blocks/raw_<mat>` tags, when they should use `c:storage_blocks/raw_<mat>` tags
![{5466E459-241E-43EB-B3A9-14D94FDA1577}](https://github.com/user-attachments/assets/b841bb80-10f7-47c7-b81b-865fe0b9cbd3)
![{03ED4853-BCAC-4E3B-9D80-60CFFD28DE4A}](https://github.com/user-attachments/assets/b70ebba2-28cc-4598-8e2b-d343e9490755)

**Comment by NielsPilgaard** [comment]
Seems like this has been resolved.
