### ISSUE TITLE
noStartupMessagesMessages blocking any message containing the word "alpha"

### ISSUE THREAD

**Issue by AlphaConqueror** [JDKDigital/utilitarian#8]
https://github.com/JDKDigital/utilitarian/blob/dbe6bd8dbba167d1b2f72d9c17aa1e7e9186efbe/src/main/java/cy/jdkdigital/utilitarian/event/EventHandler.java#L134-L143

I don't think there is a reason to block any and every message containing the word "alpha". This seems more like a band-aid solution to a problem than an actual solution.

Proposed changes:
- Disable by default.
- Let servers handle it. (Since I do not know why this was even implemented (git blame was not helpful), this might not be possible.)
- Use more a more concrete string or regular expression approach to filter out the messages you actually want to filter out, and avoid using String#contains.

**Comment by JaisDK** [comment]
I don't have "alpha" in the default config

<https://github.com/JDKDigital/utilitarian/blob/dev-1.21.0/src/main/java/cy/jdkdigital/utilitarian/Config.java#L26>

**Comment by AlphaConqueror** [comment]
I'm sorry, I got confused. I guess the FTB people cut down the original string to just "alpha" as a band-aid solution, which is causing issues on the server side. Thanks for the quick response.
